on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    strategy:
        matrix:
          include:
            - {os: "linux", arch: "x64", runson: "ubuntu-latest", hash: "12a4ce580cd2ed76e2fc8c3673d2154ebcbf2bbb1e698208d29b9b40e20f40af"}
            - {os: "windows", arch: "x64", runson: "windows-latest", hash: "a4a0fee23ee0f603aac4a3fc82561d49f8b64919c6b29ea6ccdfb8a87c6b0cad"}
            - {os: "darwin", arch: "x64", runson: "macos-13", hash: "282d0bd6d136d3adcdd3cd9c3c8efb9b6c88fd08b744ad8c26fd4d3213255b32"}
            - {os: "darwin", arch: "aarch64", runson: "macos-latest", hash: "ba57e229c0231881f85697757f1cac05c3381bc836eb80ed20404e75897c736e"}
        fail-fast: false

    runs-on: ${{ matrix.runson }}
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - run: curl -fsSL "https://synap.sh/install?hash=${{ matrix.hash }}" | bash
        if: runner.os != 'Windows'
      - run: irm https://synap.sh/install.ps1?hash=${{ matrix.hash }} | iex
        if: runner.os == 'Windows'

      - name: Build
        env:
          OPT_MODE: ReleaseFast
        run: synapse run package
      - run: mkdir package && tar -xzf out/package.tgz -C package/
      - uses: actions/upload-artifact@v4
        with:
          name: synapse-typescript-${{ matrix.os }}-${{ matrix.arch }}
          path: package/
          include-hidden-files: true # for .synapse
          if-no-files-found: error